### CNN Model for Binary Classification (Need for refactoring)

In [15]:
## Importing preprocessed dataset
import pandas as pd
import numpy as np
import pickle

#Loading the dataset
df = open("/Users/kritya/DSCI_Project/project-dsci-644-group-7-dsci_7/src/dataset/shuffle_dataset.pickle", "rb")
dataset = pickle.load(df)
df.close()

# Loading the frequent words set
df1 = open("/Users/kritya/DSCI_Project/project-dsci-644-group-7-dsci_7/src/dataset/freq_words_after_preprocessing.pickle", "rb")
freq_words = pickle.load(df1)
df1.close()

data = pd.DataFrame(dataset, columns=["Pre-processed", "label", "lemmas"])
data

Pre-processed  label  \
0       modif roo command enhanc usabl consist add on...      1   
1       add debug trace zk procedur add debug trace l...      0   
2       expos listpeerconfig getpeerconfig hbase shel...      0   
3       choos data access pattern time aspect gener a...      1   
4       distribut search mode use grpc user give sql ...      1   
...                                                  ...    ...   
13359   provid separ read write thread bookkeep serve...      1   
13360   signific perform improv per current metadata ...      1   
13361   finer grain log metric split transact split t...      0   
13362   updat atla architectur wiki new addit atla ar...      0   
13363   maven sling plugin allow instal bundl slingpo...      1   

                                                  lemmas  
0      [modif, roo, command, enhanc, usabl, consist, ...  
1      [debug, trace, zk, procedur, debug, trace, log...  
2      [expo, getpeerconfig, shell, getpeerconfig, re...  
3      [data, access, pattern, time, aspect, gener, a...  
4      [distribut, search, mode, grpc, sql, statement...  
...                                                  ...  
13359  [provid, separ, write, thread, bookkeep, serve...  
13360  [signific, perform, improv, current, metadata,...  
13361  [finer, grain, log, metric, split, transact, s...  
13362  [updat, atla, architectur, addit, atla, archit...  
13363  [sling, plugin, instal, bundl, slingpostservle...  

[13364 rows x 3 columns]

In [18]:
freq_words

['code',
 'support',
 'apach',
 'current',
 'class',
 'java',
 'sling',
 'implement',
 'file',
 'http',
 'method',
 'creat',
 'test',
 'type',
 'configur',
 'provid',
 'data',
 'chang',
 'user',
 'time',
 'client',
 'valu',
 'gener',
 'hbase',
 'string',
 'case',
 'list',
 'default',
 'properti',
 'resourc',
 'org',
 'version',
 'tabl',
 'project',
 'api',
 'servic',
 'base',
 'option',
 'log',
 'request',
 'messag',
 'queri',
 'updat',
 'remov',
 'interfac',
 'ad',
 'improv',
 'work',
 'error',
 'function',
 'exampl',
 'issu',
 'call',
 'bundl',
 'applic',
 'content',
 'process',
 'modul',
 'map',
 'requir',
 'access',
 'load',
 'result',
 'util',
 'job',
 'number',
 'handl',
 'path',
 'script',
 'document',
 'patch',
 'compon',
 'includ',
 'possibl',
 'thread',
 'region',
 'system',
 'public',
 'order',
 'featur',
 'field',
 'cluster',
 'server',
 'instanc',
 'key',
 'core',
 'store',
 'return',
 'node',
 'html',
 'jcr',
 'command',
 'main',
 'hadoop',
 'common',
 'xml',
 'jar',
 'co

In [19]:
# Importing libraries
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from tensorflow.keras.layers import Embedding
from keras.preprocessing import sequence

train = data['Pre-processed']
test = data['label']

X_train, X_test, y_train, y_test = train_test_split(train, test, test_size=0.30, random_state=42)


print('Shape of training data: ')
print(X_train.shape)
print(y_train.shape)

print('Shape of test data: ')
print(X_test.shape)
print(y_test.shape)

8922                              post code refactor clean
2676      creat script verifi releas artifact helper sc...
12540     replicationsourcemanag abl track multipl wal ...
9343      defin proper contentresolv servic map request...
13148     provid custom navig provis model featur file ...
                               ...                        
11964     revis code_convent current code_convent file ...
5191      gener report show project field defin report ...
5390      intern refactor better support meta annot met...
860       expos bucketcach valu configur bucketcach alw...
7270      provid healthcheckexecutor servic goal abl ge...
Name: Pre-processed, Length: 9354, dtype: object
8922     1
2676     0
12540    1
9343     1
13148    1
        ..
11964    0
5191     1
5390     1
860      1
7270     1
Name: label, Length: 9354, dtype: int64
Shape of training data: 
(9354,)
(9354,)
168       synchron tab model objent dbentiti editor pan...
11711     use dedic thread releas resourc

In [23]:
# max length of review calculation
maxi=-1
for i,rev in enumerate(data['Pre-processed']):
    tokens=rev.split()
    if(len(tokens)>maxi):
        maxi=len(tokens)
print(maxi)

4484


In [54]:
words_to_index = tokenizer.word_index
vocab_len = len(words_to_index)+1
embed_vector_len = 128
maxLen = 4484 #Maximum review length


In [55]:
#Tokenization
from tensorflow.keras.preprocessing.text import Tokenizer

max_words = len(X_train[1])
# Create a tokenizer object
tokenizer = Tokenizer(num_words=max_words)

# Fit the tokenizer on the training data
tokenizer.fit_on_texts(X_train)

# Convert the text data to sequences
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

# Pad the sequences to have a fixed length
from tensorflow.keras.preprocessing.sequence import pad_sequences

pad_rev= pad_sequences(X_train_seq, maxlen=maxLen, padding='post')
pad_rev.shape 

# X_train_pad = pad_sequences(X_train_seq, maxlen=maxLen, padding='post')
# X_test_pad = pad_sequences(X_test_seq, maxlen=maxLen, padding='post')

X_train_pad = pad_sequences(X_train_seq, maxlen=max_words)
X_test_pad = pad_sequences(X_test_seq, maxlen=max_words)

In [64]:
import keras
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras import layers
from tensorflow.keras.layers import Embedding
from keras.layers import InputLayer

embedding_layer = Embedding(input_dim=vocab_len, output_dim=embed_vector_len, input_length=max_words, trainable=True)

# # Building the CNN Model
model = tensorflow.keras.Sequential()    
model.add(embedding_layer)
model.add(Conv1D(64, 2, padding='same', activation='relu'))
model.add(MaxPooling1D())
model.add(Conv1D(32, 2, padding='same', activation='relu'))
model.add(MaxPooling1D())
model.add(Conv1D(16, 2, padding='same', activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(200, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
history = model.fit(X_train_pad, y_train, batch_size=128, epochs=10, validation_data=(X_test_pad, y_test))

Epoch 1/10
74/74 [==============================] - 6s 60ms/step - loss: 0.6624 - accuracy: 0.5930 - val_loss: 0.6564 - val_accuracy: 0.6077
Epoch 2/10
74/74 [==============================] - 4s 58ms/step - loss: 0.6430 - accuracy: 0.6218 - val_loss: 0.6351 - val_accuracy: 0.6404
Epoch 3/10
74/74 [==============================] - 4s 58ms/step - loss: 0.6222 - accuracy: 0.6472 - val_loss: 0.6265 - val_accuracy: 0.6484
Epoch 4/10
74/74 [==============================] - 4s 57ms/step - loss: 0.6034 - accuracy: 0.6620 - val_loss: 0.6232 - val_accuracy: 0.6504
Epoch 5/10
74/74 [==============================] - 4s 58ms/step - loss: 0.5645 - accuracy: 0.7017 - val_loss: 0.6248 - val_accuracy: 0.6469
Epoch 6/10
74/74 [==============================] - 4s 59ms/step - loss: 0.5271 - accuracy: 0.7332 - val_loss: 0.6572 - val_accuracy: 0.6416
Epoch 7/10
74/74 [==============================] - 5s 61ms/step - loss: 0.4725 - accuracy: 0.7710 - val_loss: 0.7071 - val_accuracy: 0.6509
Epoch 8/10
74

In [65]:
y_pred = model.predict(X_test_pad)
print(y_pred)

126/126 [==============================] - 0s 2ms/step
[[0.68936014]
 [0.801608  ]
 [0.6557186 ]
 ...
 [0.95120764]
 [0.9041233 ]
 [0.98501736]]


In [69]:
# Calculate metrics
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from keras.utils import to_categorical

y_pred = model.predict(X_test_pad)


# Get the actual labels for the test data
y_true = y_test

threshold = 0.6
y_pred_binary = np.where(y_pred > threshold, 1, 0)

# Generate the classification report
print('Classification Report:')
report = classification_report(y_true, y_pred_binary)
print(report)

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred_binary))

accuracy = accuracy_score(y_test, y_pred_binary)

print("Accuracy: ", accuracy)



126/126 [==============================] - 0s 2ms/step
Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.54      0.55      1608
           1       0.70      0.72      0.71      2402

    accuracy                           0.64      4010
   macro avg       0.63      0.63      0.63      4010
weighted avg       0.64      0.64      0.64      4010

Confusion Matrix:
[[ 862  746]
 [ 684 1718]]
Accuracy:  0.6433915211970075


### 

### CNN Model for Multi-class Classsification (Type of refactoring)

In [23]:
## Importing preprocessed dataset
import pandas as pd
import numpy as np
import pickle

tag = pd.read_csv("/Users/kritya/DSCI_Project/project-dsci-644-group-7-dsci_7/src/dataset/Tag.csv")
data = pd.read_csv("/Users/kritya/DSCI_Project/project-dsci-644-group-7-dsci_7/src/dataset/TextPreprocessed.csv")

data

Id                                               Text
0      5420   allow sqloper overridden valid calcit allow f...
1      5421   allow sqloper overridden valid calcit allow f...
2      5422   add support translat expess from_str to_str c...
3      5423   extend simplifi reduc express would like cove...
4      5424   add support timestampadd timestampdiff functi...
...     ...                                                ...
7939  13359  improve frameobject tostring output currently ...
7940  13360  add vector as supported type in frame conversi...
7941  13361  performance: improve vector dataframe conversi...
7942  13362  performance: improve vector dataframe conversi...
7943  13363  performance: improve vector dataframe conversi...

[7944 rows x 2 columns]

In [36]:
tag

Id                                                Tag
0       5420  extract method                                ...
1       5421  rename method                                 ...
2       5422  extract method                                ...
3       5423  extract method                                ...
4       5424  move attribute                                ...
...      ...                                                ...
13131  18551  extract method                                ...
13132  18552  rename method                                 ...
13133  18553  extract method                                ...
13134  18554  move attribute                                ...
13135  18555  rename method                                 ...

[13136 rows x 2 columns]

In [24]:
label = tag.head(7944)
label

Id                                                Tag
0      5420  extract method                                ...
1      5421  rename method                                 ...
2      5422  extract method                                ...
3      5423  extract method                                ...
4      5424  move attribute                                ...
...     ...                                                ...
7939  13359  rename method                                 ...
7940  13360  extract method                                ...
7941  13361  rename class                                  ...
7942  13362  rename method                                 ...
7943  13363  move method                                   ...

[7944 rows x 2 columns]

In [25]:
print(len(label['Tag'].unique()))

14


In [26]:
# Importing libraries
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from tensorflow.keras.layers import Embedding
from keras.preprocessing import sequence

X_train, X_test, y_train, y_test = train_test_split(data["Text"], label["Tag"], test_size=0.30, random_state=42)

print('Shape of training data: ')
print(X_train.shape)
print(y_train.shape)
print('Shape of test data: ')
print(X_test.shape)
print(y_test.shape)

Shape of training data: 
(5560,)
(5560,)
Shape of test data: 
(2384,)
(2384,)


In [27]:
from tensorflow.keras.preprocessing.text import Tokenizer
max_words = len(X_train[1])
# Create a tokenizer object
tokenizer = Tokenizer(num_words=max_words)

# Fit the tokenizer on the training data
tokenizer.fit_on_texts(X_train)

words_to_index = tokenizer.word_index
vocab_len = len(words_to_index)+1
embed_vector_len = 128
maxLen = 4484 #Maximum review length

In [28]:
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.utils import pad_sequences

# Convert the text data to sequences
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

X_train_pad = pad_sequences(X_train_seq, maxlen=max_words)
X_test_pad = pad_sequences(X_test_seq, maxlen=max_words)

# create an instance of the LabelEncoder class
le = LabelEncoder()

# fit the encoder to the labels and transform them to numerical values
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

# create an instance of the OneHotEncoder
encoder = OneHotEncoder()

# fit the encoder on y_train and transform y_train and y_test
y_train_one_hot = encoder.fit_transform(y_train_encoded.reshape(-1, 1))
y_test_one_hot = encoder.transform(y_test_encoded.reshape(-1, 1))


In [12]:
import tensorflow as tf
from tensorflow import keras
from keras import layers

embedding_layer = Embedding(input_dim=vocab_len, output_dim=embed_vector_len, input_length=max_words, trainable=True)

model = keras.Sequential([
    layers.Embedding(input_dim=vocab_len, output_dim=embed_vector_len, input_length=max_words, trainable=True),
    layers.Conv1D(32, 3, activation='relu', padding='same'),
    layers.MaxPooling1D(pool_size=2),
    layers.Conv1D(64, 3, activation='relu', padding='same'),
    layers.MaxPooling1D(pool_size=2),
    layers.Flatten(),
    layers.Dense(256, activation='relu'),
    layers.Dense(14, activation='softmax')
])

# Compile the model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
history = model.fit(X_train_pad, y_train_encoded, batch_size=32, epochs=20)


Epoch 1/20
174/174 [==============================] - 12s 62ms/step - loss: 2.0618 - accuracy: 0.3167
Epoch 2/20
174/174 [==============================] - 10s 60ms/step - loss: 2.0254 - accuracy: 0.3227
Epoch 3/20
174/174 [==============================] - 10s 60ms/step - loss: 1.9908 - accuracy: 0.3353
Epoch 4/20
174/174 [==============================] - 10s 60ms/step - loss: 1.9089 - accuracy: 0.3651
Epoch 5/20
174/174 [==============================] - 11s 61ms/step - loss: 1.7777 - accuracy: 0.4018
Epoch 6/20
174/174 [==============================] - 11s 61ms/step - loss: 1.6413 - accuracy: 0.4491
Epoch 7/20
174/174 [==============================] - 10s 59ms/step - loss: 1.5051 - accuracy: 0.4844
Epoch 8/20
174/174 [==============================] - 10s 60ms/step - loss: 1.3727 - accuracy: 0.5362
Epoch 9/20
174/174 [==============================] - 11s 63ms/step - loss: 1.2668 - accuracy: 0.5727
Epoch 10/20
174/174 [==============================] - 11s 61ms/step - loss: 1.173

In [13]:
y_test_encoded

array([13, 13,  7, ...,  1,  5,  1])

In [14]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# Converting type of columns to category
y_test = y_test.astype('category')

tag = y_test.cat.codes

# Reshape tag to have one column
tag = tag.values.reshape(-1, 1)

enc = OneHotEncoder()

# Fit and transform the encoded columns
enc_data = enc.fit_transform(tag).toarray()

In [35]:
from sklearn.metrics import hamming_loss
from sklearn import preprocessing
import numpy as np
from sklearn.metrics import confusion_matrix

def subset_accuracy(y_true, y_pred):
    print('Subset accuracy: {0}'.format(sklearn.metrics.accuracy_score(y_true, y_pred, normalize=True, sample_weight=None)))

def hamming_loss(y_true, y_pred):
    print('Hamming loss: {0}'.format(sklearn.metrics.hamming_loss(y_true, y_pred)))

def hamming_score(y_true, y_pred):
    print('Hamming score: {0}'.format(hamming_score(y_true, y_pred)))


y_true = y_test_one_hot

y_pred = model.predict(X_test_pad)
threshold = 0.5
y_pred_binary = np.where(y_pred > threshold, 1, 0)
y_pred = y_pred_binary
y_true = preprocessing.label_binarize(y_test, classes=np.unique(y_test))

subset_accuracy(y_true, y_pred)
hamming_loss(y_true, y_pred)
hamming_score(y_true, y_pred)


ImportError: cannot import name 'subset_accuracy' from 'sklearn.metrics' (/Users/kritya/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/__init__.py)

In [32]:
from sklearn.metrics import multilabel_confusion_matrix

y_true = y_test_one_hot

y_pred = model.predict(X_test_pad)
threshold = 0.5
y_true = preprocessing.label_binarize(y_test, classes=np.unique(y_test))
y_pred_binary = np.where(y_pred > threshold, 1, 0)
y_pred = y_pred_binary

print('Confusion Matrix:')
confusion_matrix = multilabel_confusion_matrix(y_true, y_pred)
print(multilabel_confusion_matrix(y_true, y_pred))

75/75 [==============================] - 1s 10ms/step
Confusion Matrix:
[[[2344    6]
  [  34    0]]

 [[1219  376]
  [ 585  204]]

 [[2351    8]
  [  25    0]]

 [[2140   94]
  [ 145    5]]

 [[2321   14]
  [  49    0]]

 [[2151   48]
  [ 184    1]]

 [[2232   39]
  [ 110    3]]

 [[1991  134]
  [ 251    8]]

 [[2335   13]
  [  35    1]]

 [[2329   10]
  [  45    0]]

 [[2358    2]
  [  24    0]]

 [[2351    5]
  [  28    0]]

 [[2142   90]
  [ 144    8]]

 [[1558  331]
  [ 420   75]]]


In [33]:
total_correct = 0
total_labels = 0

for i in range(14):
    cm = confusion_matrix[i]
    correct = np.sum(np.diag(cm))
    total_correct += correct
    total_labels += np.sum(cm)

hamming_score = total_correct / total_labels
print('Hamming score: {0}'.format(hamming_score))


Hamming score: 0.9026546021093
